### ISSUE TITLE
Support Declare Transactions

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape-starknet#32]
### Overview

https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/definitions/transaction_type.py#L5

### Specification

May have to poke around Starknet.py or cairo-lang to fully understand.
It is for changing code or putting some code up or something like that...

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by unparalleled-js** [comment]
@ca11ab1e Can you help me fill this in?
And then in your PR, put `fixes: #32`?

**Comment by ca11ab1e** [comment]
Interesting links:
- https://docs.starknet.io/docs/Contracts/contract-classes/
- https://docs.starknet.io/docs/Blocks/transactions#declare-transaction

They are needed to *deploy* the code object of a contract on the network, without actually instantiating it (think of it like pushing the code of  `class Foo: ...`). A declared contract can be **deploy**ed later (think of like like an instance of the `Foo` class: `foo = Foo()`).

**Comment by ca11ab1e** [comment]
In substance, we need something like:

```python
token = ape.project.MyToken

# Declare the contract
# Using **kwargs to denote the capability to pass a sender, or maybe other args
declaration = token.declare(**kwargs)

# Later, deploy an instance of that contract's declaration
deployment = declaration.deploy(*args, **kwargs)
# I guess it should also be possible to use that syntax:
# deployment = token.deploy(declaration, *args, **kwargs) 
```

**Comment by ca11ab1e** [comment]
Current implementations:
- starknet.py: [here](https://github.com/software-mansion/starknet.py/blob/0.3.2-alpha/starknet_py/net/models/transaction.py#L10), and [there](https://github.com/software-mansion/starknet.py/blob/0.3.2-alpha/starknet_py/net/client.py#L275)
- starknet-devenet: [here](https://github.com/Shard-Labs/starknet-devnet/blob/v0.2.3/starknet_devnet/starknet_wrapper.py#L187), [there](https://github.com/Shard-Labs/starknet-devnet/blob/v0.2.3/starknet_devnet/blueprints/gateway.py#L30), and [there](https://github.com/Shard-Labs/starknet-devnet/blob/v0.2.3/test/util.py#L99)

**Comment by unparalleled-js** [comment]
Someday, I would like plugins to be able to customize the `ContractType` class more. Today, however, it isn't possible.

What do you think of the `declare()` method being on the account? Like:

```python
token = ape.project.MyToken
account = ape.accounts.load("Me")
contract_declaration = account.declare(token, **kwargs)

# NOTE: We already have the ability to 'deploy()' from with the account as the calling object
contract_deployment = account.deploy(contract_declaration)
```

**Comment by ca11ab1e** [comment]
> What do you think of the `declare()` method being on the account? Like:

Having the same symmetry as `deploy()` would be perfect, but we can go with the account-only implementation to start.

**Comment by unparalleled-js** [comment]
Realized it does not make sense in the account since you use the sender of `1` so it will just be a provider method for now, until we have the support in ape.
