### ISSUE TITLE
Leverage stdout from starknet-devnet provider process

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape-starknet#44]
### Overview

Get the output from the starknet-devnet process and put it somewhere

### Specification

* Grab the stdout and stderr of the starknet-devnet process and put it in file (like in `.ape/starknet/provider/stdout.logs`)

Might be a way to use `Popen`

### Dependencies

Might need to update  core ape: https://github.com/ApeWorX/ape/blob/main/src/ape/api/providers.py#L1021

**Comment by 0xSidius** [comment]
just to be extra clear on the use case, storing devnet stdout locally is fine, but the most common use case remains to stream it to Ape/Pytest standard loggers during test runs or deployments

**Comment by unparalleled-js** [comment]
@0xSidius With these changes, you can run with `-v debug` and the output from the process will be included in Ape's normal logger's output.

The filtering useful logs feature in test runs may be a little more complicated. Might be in the form of a pytest hook implementation.

**Comment by unparalleled-js** [comment]
That got done in Core Ape!
The logs can be found i your .ape data directory
