### ISSUE TITLE
Optimize the plugin where possible

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape-starknet#45]
### Overview

We all know Starknet is pretty slow currently.
Let's figure out way to optimize on our end to improve the experience.

### Specification

- [ ] Spend time finding ways to optimize
- [ ] Fix things as we can
- [ ] For bigger optimizations, create new tickets
- [ ] Points-box this to 3 points to prevent ticket scope creep.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by 0xSidius** [comment]
The bottlenecks are clearly during fixture contract deployments and other interactions with the devnet (like declaration txs). For 2 declarations, 1 contract deployment and 1 simple related test case, a Pytest run currently averages around 3.30 minutes.

![image](https://user-images.githubusercontent.com/100469911/176514117-0b73d380-972a-436d-824c-97337d018922.png)

![image](https://user-images.githubusercontent.com/100469911/176514060-4c122443-8596-41a1-af2c-de6789b8cc66.png)

Pre-deploying accounts or making tests run faster is not where the bottleneck is to be found

**Comment by johnson2427** [comment]
@0xSidius can you paste the contracts here so I can reproduce your system setup? Maybe send over a screenshot of your folder tree? Also, we do have a test or two failing currently on our side that we are working on, and some of it is hanging. Might be the cause of your headaches.

**Comment by 0xSidius** [comment]
> @0xSidius can you paste the contracts here so I can reproduce your system setup? Maybe send over a screenshot of your folder tree? Also, we do have a test or two failing currently on our side that we are working on, and some of it is hanging. Might be the cause of your headaches.

@unparalleled-js has access to our repo, we also talked with her today about where to expect the bottlenecks as well as setting some expectations for how much things can be improved. She can help you on both fronts I think

our contract structures is the following:

![image](https://user-images.githubusercontent.com/100469911/176723301-8ecbe568-36ad-46cd-a067-41ef747c93c4.png)

**Comment by johnson2427** [comment]
@0xSidius Thank you! I'll set up a cairo test and start working through it. Last I checked, we had some issues with cairo and our yaml setup. Could be the root here.

**Comment by unparalleled-js** [comment]
I think this test is good candidate to test against: def test_declare_then_deploy(account, chain, project, provider, factory_contract_container):

It is a very slow test and does declares and deploys in it.

**Comment by johnson2427** [comment]
@unparalleled-js I've been searching for the source of this for most of the day, and I can't figure out why. This is running in 25 seconds (on averagish).
