### ISSUE TITLE
Allow to estimate gas cost on the devnet

### ISSUE THREAD

**Issue by ca11ab1e** [ApeWorX/ape-starknet#52]
It is possible to estimate gas cost from the devnet since several versions now, maybe could we remove that condition block then?

https://github.com/ApeWorX/ape-starknet/blob/573ffec279b513154a2240e8cae9720f082c1309/ape_starknet/provider.py#L163-L165

I guess it would unlock part of our tests at SithSwap.

Note: I open an issue because I tried removing that code, and it broke all tests:

```python
BadRequest: HTTP error ocurred. Status: 500. Text: {"message":"Error at pc=0:6:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:1324)\nUnknown location (pc=0:1301)\nUnknown location (pc=0:611)\nUnknown location (pc=0:889)\n\nTraceback (most recent call last):\n  File \"<hint0>\", line 3, in <module>\nAssertionError: assert_not_zero failed: 0 = 0.","status_code":500}
```

Maybe opened PRs will help, especially #46? :thinking:

**Comment by 0xSidius** [comment]
to help guide @unparalleled-js for this feature:

exhibit A
![image](https://user-images.githubusercontent.com/100469911/177145820-960efc83-9127-4b0e-9263-f758742e7a40.png)


exhibit B
![image](https://user-images.githubusercontent.com/100469911/177145569-031de3ab-fe07-4964-bd06-94bc1640d350.png)
