### ISSUE TITLE
Use the mypy configuration file

### ISSUE THREAD

**Issue by ca11ab1e** [ApeWorX/ape-starknet#53]
### Overview

There are lots of `type: ignore` comments in imports.

Would you be interested in a PR to create the mypy configuration file to skip that [specific check](https://mypy.readthedocs.io/en/stable/config_file.html#confval-ignore_missing_imports)?

### Specification

Here is the minimal `mypy.ini` file:

```ini
[mypy]
ignore_missing_imports = true
```

And a complete example (my preference):

```ini
[mypy]
# Ensure we know what we do
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
# warn_unreachable = true  (to check)

# Imports management
ignore_missing_imports = true
follow_imports = normal
```

### Dependencies

None.

**Comment by unparalleled-js** [comment]
You can do this using `pyproject.toml` I believe.

But honestly, would like this plugin to be the same as the other plugins. Such changes from come from the top down, starting core Ape and including the Plugin Template repo.

**Comment by ca11ab1e** [comment]
You are right. I'll start for the top then :)

**Comment by unparalleled-js** [comment]
I am changing my mind a little...

If this plugin is particular notorious for them ,we can disable them here only, just use the `pyproject.toml` file

**Comment by ca11ab1e** [comment]
Actually, I am more thinking about using the plugin. I do not want to disable anything but to improve mypy checks.
