### ISSUE TITLE
Support switching providers in-test

### ISSUE THREAD

**Issue by 0xSidius** [ApeWorX/ape-starknet#61]
Currently, support for switching network providers "in-flight" during the execution of test code remains broken, e.g. within a test case, can't jump from interacting with a Hardhat VM contract to interacting with a (Starknet) Devnet contract, even when forcibly selecting the new provider, the previous one will still be used to interact with the Starknet network thereby failing the test run

**Comment by unparalleled-js** [comment]
We will add some integration tests and ensure this is functioning, but it seems odd that it wouldn't work. You are trying something like:

```python
with networks.ethereum.local.use_provider("hardhat"):
    # Do stuff

with networks.starknet.local.use_provider("starknet"):
   # Do stuff
```

**Comment by 0xSidius** [comment]
> We will add some integration tests and ensure this is functioning, but it seems odd that it wouldn't work. You are trying something like:
> 
> ```python
> with networks.ethereum.local.use_provider("hardhat"):
>     # Do stuff
> 
> with networks.starknet.local.use_provider("starknet"):
>    # Do stuff
> ```

indeed, you had committed that solution in our repo: https://github.com/SithSwap/core-amm/commit/9086a5e2ddb955e05990c02cfe68f63f962dcc35

but it has continued to fail thereafter, you can try it on `master` branch:
- `./just clean && ./just setup`
- `./just tests test_SithSwapV1Library.py`
